### ISSUE TITLE
Please start using tags

### ISSUE THREAD

**Issue by g4b0** [unisolutions/silverstripe-copybutton#7]
Tags are useful for module versioning, please start deploying versions

**Comment by uniun** [comment]
I've finally created three tags and releases:

0.8.0 - for SS 3.0.* (with GridFieldDetailFormCustom class)
0.9.0 - for SS 3.1.* (with GridFieldDetailFormCustom class)
1.0.0 - for SS 3.1.* (without GridFieldDetailFormCustom class)
